name: Test vcpkg on arm64-ios

on:
  push:
    branches:
      - "vcpkg-arm64-ios"

jobs:
  generate-bridge-linux:
    uses: ./.github/workflows/bridge.yml

  test-vcpkg-arm64-ios:
    needs: [generate-bridge-linux]
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - {
              arch: aarch64,
              target: aarch64-apple-ios,
              os: macos-latest,
              extra-build-features: "",
            }
    steps:
      - name: Install dependencies
        run: |
          brew install nasm yasm

      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: vcpkg-deps

      - name: Setup vcpkg with Github Actions binary cache
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgGitCommitId: "8eb57355a4ffb410a2e94c07b4dca2dffbee8e50"

      - name: Install vcpkg dependencies
        run: |
          $VCPKG_ROOT/vcpkg install --triplet arm64-ios --x-install-root="$VCPKG_ROOT/installed"
#          $VCPKG_ROOT/vcpkg install --triplet arm64-ios --x-install-root="$VCPKG_ROOT/installed" --x-cmake-args=--trace-expand --debug
#          pushd $VCPKG_ROOT
#          tar czvf $OLDPWD/vcpkg-arm64-ios.tar.gz buildtrees installed
#          popd
        shell: bash

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal # minimal component installation (ie, no documentation)

#      - name: Install flutter rust bridge deps
#        shell: bash
#        run: |
#          cargo install flutter_rust_bridge_codegen --version 1.80.1 --features "uuid"
#          pushd flutter && flutter pub get && popd
#          ~/.cargo/bin/flutter_rust_bridge_codegen --rust-input ./src/flutter_ffi.rs --dart-output ./flutter/lib/generated_bridge.dart --c-output ./flutter/ios/Runner/bridge_generated.h

      - name: Build rustdesk lib
        run: |
          rustup target add ${{ matrix.job.target }}
          cargo build --features flutter --release --target aarch64-apple-ios --lib

#      - name: Publish Release
#        uses: softprops/action-gh-release@v1
#        with:
#          prerelease: true
#          tag_name: "test-arm64-ios"
#          files: |
#            ./vcpkg-arm64-ios.tar.gz
